[core] Fix `npm run build` not working on Windows (#5711)
* Fix: stylelint throws error on Windows

```
> mantine-a91763c0e2@7.5.1 stylelint
> stylelint '**/*.css' --cache

Error: No files matching the pattern "'**/*.css'" were found.
```
Reference: https://github.com/stylelint/stylelint/issues/4178#issuecomment-515887546

* Fix: fast-glob doesn't support Windows paths

References:
- https://github.com/mrmlnc/fast-glob/issues/237#issuecomment-546057189
- https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#how-to-write-patterns-on-windows

* fix: `touch` is not recognized as an internal or external command

* fix: rimraf throws `Illegal characters in path` error

`rimraf` doesn't treat arguments as glob patterns by default, and Windows doesn't allow `*` character in paths.

From the docs
```
  -G --no-glob         Treat arguments as literal paths, not globs (default)
  -g --glob            Treat arguments as glob patterns
```